Feature/28519 design update
bcc-code/bmm-app pull request #25
Opened 2021-05-27 12:31 UTC by kkuepper

2021-06-07 11:15 UTC, olivereisenhut requested changes

2021-06-07 11:15 UTC, olivereisenhut commented on BMM.UI.Android/Resources/drawable/icon_download_done.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Can you delete the .png versions of all the assets now added as SVG drawable?

2021-06-07 12:12 UTC, kkuepper commented on BMM.Core/BMM.Core.csproj
> +    <Folder Include="Implementations\MyTracks" />
removed

2021-06-07 12:14 UTC, kkuepper commented on BMM.UI.Android/Application/Bindings/MvxCardCircle.cs
> +}
it's used in listitem_tracklist_header.xml
`card_view:MvxBind="Visibility Visibility(ShowImage); CardCircle UseCircularImage">`

2021-06-07 12:16 UTC, kkuepper commented on BMM.UI.Android/Application/Fragments/AlbumFragment.cs
>          public override void OnCreateOptionsMenu(IMenu menu, MenuInflater inflater)
good catch

2021-06-07 12:30 UTC, kkuepper commented on BMM.UI.Android/Application/TemplateSelectors/TrackListTemplateSelector.cs
> +    [Obsolete]
deleted PodcastTemplateSelector and TrackCollectionSelector.
This selector though should not have been marked as obsolete.

2021-06-07 12:30 UTC, kkuepper commented on BMM.UI.Android/Application/TemplateSelectors/PodcastTemplateSelector.cs
> +    [Obsolete]
deleted

2021-06-07 13:13 UTC, kkuepper commented on BMM.UI.Android/Application/ValueConverters/DownloadStatusVisibilityValueConverter.cs
> +        protected abstract bool IsIt(Track track);
is HasItRightStatus better understandable?

2021-06-07 13:13 UTC, kkuepper commented on BMM.UI.Android/Application/ValueConverters/VisibleOrHiddenValueConverter.cs
> +    public class VisibilityAndValueConverter : MvxBaseVisibilityValueConverter<bool>
removed

2021-06-07 13:18 UTC, kkuepper commented on BMM.UI.Android/BMM.UI.Droid.csproj
> +    <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
I think I did it manually. Reverted it

2021-06-07 13:58 UTC, kkuepper commented on BMM.UI.Android/Application/Bindings/MvxCardCircle.cs
> +}
add comment

2021-06-07 16:09 UTC, kkuepper commented on BMM.Api/Implementation/Models/Album.cs
> +        public string Description { get; set; }
still needs to be implemented for Android

2021-06-08 06:26 UTC, olivereisenhut commented on BMM.Api/Implementation/Models/Playlist.cs
> +        public string Description { get; set; }
No not yet

2021-06-08 07:36 UTC, olivereisenhut commented on BMM.UI.iOS/Application/Helpers/GradientView.cs
> +    // https://stackoverflow.com/questions/17555986/cagradientlayer-not-resizing-nicely-tearing-on-rotation
Yes

2021-06-08 07:36 UTC, olivereisenhut commented on BMM.UI.iOS/Application/ViewController/ContributorViewController.cs
> +            // set.Bind(TrackTableTitle).To(vm => vm.TextSource).WithConversion<MvxLanguageConverter>("HeaderText");
Removed it

2021-06-08 07:36 UTC, olivereisenhut commented on BMM.UI.iOS/BMM.UI.iOS.csproj
> +    <BundleResource Include="Resources\icon_bell.png" />
Did the renaming

2021-06-08 07:43 UTC, olivereisenhut commented on BMM.Core/ViewModels/ITrackListViewModel.cs
> +    public interface ITrackListViewModel
The `ITrackListDisplayable` represents a document inside of a list which has a title and a cover. I don't think there is a benefit by putting everything into a mega Interface which destroys the benefits of interfaces which with you can enforce as little logic as needed and combine them.

2021-06-08 11:42 UTC, kkuepper commented on BMM.Core/ViewModels/ITrackListViewModel.cs
> +    public interface ITrackListViewModel
When it's not the same, then we shouldn't do it

2021-06-08 11:44 UTC, kkuepper commented on BMM.UI.iOS/Application/ViewController/PodcastViewController.cs
> +            // todo I think in podcasts it should be play instead of shuffle
replace it with Play action instead

2021-06-08 12:06 UTC, olivereisenhut commented on BMM.UI.iOS/Application/ViewController/PodcastViewController.cs
> +            // todo I think in podcasts it should be play instead of shuffle
Implementation done for iOS. Can you do Android @kkuepper?

2021-06-08 15:23 UTC, kkuepper commented on BMM.UI.iOS/Application/ViewController/PodcastViewController.cs
> +            // todo I think in podcasts it should be play instead of shuffle
Android is done

2021-06-08 15:50 UTC, merged