Streak fixes
bcc-code/bmm-app pull request #422
Opened 2023-06-07 16:17 UTC by akrol95

2023-06-07 19:58 UTC, kkuepper requested changes

2023-06-07 19:58 UTC, kkuepper commented on BMM.Core/Implementations/PlayObserver/Streak/StreakObserver.cs
>                          new Dictionary<string, object>
can you add the id of the TrackPlayedEvent?

2023-06-07 19:58 UTC, kkuepper commented on BMM.Core/Implementations/PlayObserver/PlayStatistics.cs
> +                    Id = Guid.NewGuid(),
this goes against using the same id

2023-06-09 13:59 UTC, akrol95 commented on BMM.Core/Implementations/PlayObserver/PlayStatistics.cs
> +                    Id = Guid.NewGuid(),
We don't need it anymore

2023-06-09 14:14 UTC, kkuepper approved these changes

2023-06-09 16:16 UTC, merged